// <auto-generated />
namespace CI.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class New1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(New1));
        
        string IMigrationMetadata.Id
        {
            get { return "201310201658038_New1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
