// <auto-generated />
namespace CI.DAL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Test2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Test2));
        
        string IMigrationMetadata.Id
        {
            get { return "201311171029026_Test2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
